#CONVERT IMAGE TO RGBA WITH 8 BIT PER SAMPLE
CONVERT_TO_RGBA8 ?= 1
#IMAGE TO BE DECODED
INPUT_IMG ?= input.png
#DECODED IMAGE
OUTPUT_IMG ?= output.raw
#DECODED IMAGE INFO
OUTPUT_INFO ?= output_info.raw
